---

- name: Set Docker container parameters
  set_fact:
    nextcloud_container_parameters:
      name: "{{ nextcloud_name }}"
      image: "{{ nextcloud_image }}"
      state: started
      published_ports: "{{ nextcloud_ports }}"
      volumes: "{{ nextcloud_volumes }}"
      env: "{{ nextcloud_environment_variables }}"

- name: Create NextCloud container
  docker_container: "{{ nextcloud_container_parameters | combine(nextcloud_docker_additional_options) }}"
  register: nextcloud_container
