---

- name: Create NextCloud directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nextcloud_directory }}"
    - "{{ nextcloud_directory }}/app"
    - "{{ nextcloud_directory }}/build"

- name: Copy Dockerfile folder
  copy:
    src: "{{ nextcloud_build_folder }}"
    dest: "{{ nextcloud_directory }}/build"

- name: Build NextCloud Image
  docker_image:
    name: "{{ nextcloud_image }}"
    build:
      path: "{{ nextcloud_directory }}/build/{{ nextcloud_build_folder }}"
    source: build
  when: nextcloud_build_image

- name: Set Docker container parameters
  set_fact:
    nextcloud_container_parameters:
      name: "{{ nextcloud_name }}"
      image: "{{ nextcloud_image }}"
      state: started
      published_ports: "{{ nextcloud_ports }}"
      volumes:
        - "{{ nextcloud_directory }}/app:/var/www/html"
      env: "{{ nextcloud_environment_variables }}"

- name: Create NextCloud container
  docker_container: "{{ nextcloud_container_parameters | combine(nextcloud_docker_additional_options) }}"
  register: nextcloud_container

- name: Wait for NextCloud start
  wait_for:
    port: "{{ nextcloud_ports[0].split(':')[0] }}"
    host: "{{ nextcloud_container.container.NetworkSettings.IPAddress }}"
    timeout: 600
